services:
  - type: web
    name: faculty-finder
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn vector_api:app --host 0.0.0.0 --port ${PORT}
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
